{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "7.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.4.0.aar",
          "url": "viewbinding-7.4.0.aar",
          "size": 2224,
          "sha512": "ecf362743264c10cdc2a8b9f56b3af3ce5d9824dfc87d3d5679095768e5855c65ae788713912d879361d63fbec295ce85a69baef4ec818e7603b3b46a75ff413",
          "sha256": "da3b97b183fbc2aa0cb8ebd9173fc0fa425083cf9590aa4f3b6073b89c4d9d9c",
          "sha1": "3103c8bd292b07f9f492c28f7f6580874ed65f33",
          "md5": "dfbc4b5d3bee24bf9e719c13eb39952e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.4.0.aar",
          "url": "viewbinding-7.4.0.aar",
          "size": 2224,
          "sha512": "ecf362743264c10cdc2a8b9f56b3af3ce5d9824dfc87d3d5679095768e5855c65ae788713912d879361d63fbec295ce85a69baef4ec818e7603b3b46a75ff413",
          "sha256": "da3b97b183fbc2aa0cb8ebd9173fc0fa425083cf9590aa4f3b6073b89c4d9d9c",
          "sha1": "3103c8bd292b07f9f492c28f7f6580874ed65f33",
          "md5": "dfbc4b5d3bee24bf9e719c13eb39952e"
        }
      ]
    }
  ]
}
