{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.5.5.aar",
          "url": "fragment-ktx-1.5.5.aar",
          "size": 28824,
          "sha512": "3d2411f283b84d1ec002bfb6285d7b5a5c9bd656a2fe786fd0d2cffd4d876760b8f685089eef856cb14ca1a09684bd3c40029e56c5e291fcefeb86d87efe1f7a",
          "sha256": "9a7064335312237b45cda04b898139e71361eb7288ec8b2a38c4bdb4befe088e",
          "sha1": "55eb7ddff18b76f8e14432b94d7d07245ebab488",
          "md5": "c83d5ca8b64cf3d654b18c040a1849bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.5.5.aar",
          "url": "fragment-ktx-1.5.5.aar",
          "size": 28824,
          "sha512": "3d2411f283b84d1ec002bfb6285d7b5a5c9bd656a2fe786fd0d2cffd4d876760b8f685089eef856cb14ca1a09684bd3c40029e56c5e291fcefeb86d87efe1f7a",
          "sha256": "9a7064335312237b45cda04b898139e71361eb7288ec8b2a38c4bdb4befe088e",
          "sha1": "55eb7ddff18b76f8e14432b94d7d07245ebab488",
          "md5": "c83d5ca8b64cf3d654b18c040a1849bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-ktx-1.5.5-sources.jar",
          "url": "fragment-ktx-1.5.5-sources.jar",
          "size": 6437,
          "sha512": "57ba3c7a5be2637bab276975f55d8c27190a3dd2f3f68a2e11997bbeded6e70c4322df7480771716c03b51f67de6f9b650b0334e2626e235c61070576143f1ec",
          "sha256": "fdc50d74e3b70712f8e4ed39c60fc1a3b613bb49e9a8a89fc53ac35926a3e823",
          "sha1": "656ee3b3618f377f8671e3a678a0fce0c8f56b1e",
          "md5": "582c3688a9fe6dd15b2b099ebe0d3b55"
        }
      ]
    }
  ]
}